# ***NAIVE BAYES***

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.datasets import load_wine
from sklearn.preprocessing import OrdinalEncoder

from sklearn.naive_bayes import (
    GaussianNB,
    CategoricalNB,
    BernoulliNB,
    MultinomialNB,
    ComplementNB
)

from sklearn.feature_extraction.text import CountVectorizer

# HELPER FUNCTION
def evaluate_model(name, model, X_train, X_test, y_train, y_test):

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print("\n" + "="*60)
    print(name.upper())
    print("="*60)

    print("\nAccuracy:")
    print(round(accuracy_score(y_test, y_pred),4))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    if hasattr(model, "class_count_"):
        print("\nClass Count:")
        print(model.class_count_)

    if hasattr(model, "class_prior_"):
        print("\nClass Prior:")
        print(model.class_prior_)

    if hasattr(model, "feature_log_prob_"):
        print("\nFeature Log Probabilities:")
        print(model.feature_log_prob_)

    return model

***1. GAUSSIAN NAIVE BAYES***

In [6]:
print("\n\n########## 1. GAUSSIAN NB ##########")
# USE WHEN FEATURES ARE NUMERICAL
X, y = load_wine(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

gnb = GaussianNB()

evaluate_model(
    "Gaussian Naive Bayes",
    gnb,
    X_train,
    X_test,
    y_train,
    y_test
)

# observe learned statistics

print("\nMeans (theta_):")
print(gnb.theta_)

print("\nVariance:")
print(gnb.var_)



########## 1. GAUSSIAN NB ##########

GAUSSIAN NAIVE BAYES

Accuracy:
1.0

Confusion Matrix:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36


Class Count:
[45. 57. 40.]

Class Prior:
[0.31690141 0.40140845 0.28169014]

Means (theta_):
[[1.37262222e+01 1.97733333e+00 2.45000000e+00 1.67444444e+01
  1.06977778e+02 2.83977778e+00 2.97755556e+00 2.99777778e-01
  1.92444444e+00 5.42288889e+00 1.06400000e+00 3.16066667e+00
  1.09637778e+03]
 [1.22854386e+01 1.99578947e+00 2.24122807e+00 2.03368421e+01
  9.61754386e+01 2.26385965e+00 2.08456140e+00 3.58421053e-01
  1.65789474e+00 3.10894737e+00 1.0606315

***2. CATEGORICAL NAIVE BAYES***

In [7]:
print("\n\n########## 2. CATEGORICAL NB ##########")
# USE WHEN FEATURES ARE CATEGORIES
df_cat = pd.DataFrame({

    "Gender":[
        "M","F","M","F","M","F","M","F",
        "M","F","M","F"
    ],

    "City":[
        "Mumbai","Pune","Mumbai","Delhi",
        "Delhi","Pune","Mumbai","Delhi",
        "Mumbai","Pune","Delhi","Delhi"
    ],

    "Placed":[
        "Yes","No","Yes","No",
        "Yes","No","Yes","No",
        "Yes","No","Yes","No"
    ]
})

X = df_cat[["Gender","City"]]
y = df_cat["Placed"]

encoder = OrdinalEncoder()

X = encoder.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

cnb = CategoricalNB()

evaluate_model(
    "Categorical Naive Bayes",
    cnb,
    X_train,
    X_test,
    y_train,
    y_test
)



########## 2. CATEGORICAL NB ##########

CATEGORICAL NAIVE BAYES

Accuracy:
1.0

Confusion Matrix:
[[1 0]
 [0 3]]

Classification Report:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         1
         Yes       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4


Class Count:
[5. 3.]

Feature Log Probabilities:
[array([[-0.15415068, -1.94591015],
       [-1.60943791, -0.22314355]]), array([[-0.69314718, -2.07944154, -0.98082925],
       [-1.09861229, -0.69314718, -1.79175947]])]


CategoricalNB()

***3. BERNOULLI NAIVE BAYES***

In [8]:
print("\n\n########## 3. BERNOULLI NB ##########")
# USE WHEN FEATURES ARE BINARY (0/1)
df_ber = pd.DataFrame({

    "good":[1,1,0,0,1,0,1,0,1,0],
    "bad":[0,0,1,1,0,1,0,1,0,1],
    "movie":[1,1,1,1,1,1,1,1,1,1],

    "positive":[1,1,0,0,1,0,1,0,1,0]

})

X = df_ber.drop("positive",axis=1)
y = df_ber["positive"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

bnb = BernoulliNB()

evaluate_model(
    "Bernoulli Naive Bayes",
    bnb,
    X_train,
    X_test,
    y_train,
    y_test
)



########## 3. BERNOULLI NB ##########

BERNOULLI NAIVE BAYES

Accuracy:
1.0

Confusion Matrix:
[[1 0]
 [0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3


Class Count:
[4. 3.]

Feature Log Probabilities:
[[-1.79175947 -0.18232156 -0.18232156]
 [-0.22314355 -1.60943791 -0.22314355]]


BernoulliNB()

***4. MULTINOMIAL NAIVE BAYES***

In [9]:
print("\n\n########## 4. MULTINOMIAL NB ##########")
# USE FOR TEXT COUNTS
reviews = [

    "good movie",
    "great movie",
    "awesome film",
    "fantastic movie",
    "excellent film",

    "bad movie",
    "terrible film",
    "worst movie",
    "boring film",
    "poor movie"

]

labels = [1,1,1,1,1,0,0,0,0,0]

cv = CountVectorizer()

X = cv.fit_transform(reviews)
y = labels

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

mnb = MultinomialNB()

evaluate_model(
    "Multinomial Naive Bayes",
    mnb,
    X_train,
    X_test,
    y_train,
    y_test
)

print("\nVocabulary:")
print(cv.get_feature_names_out())




########## 4. MULTINOMIAL NB ##########

MULTINOMIAL NAIVE BAYES

Accuracy:
0.3333

Confusion Matrix:
[[0 2]
 [0 1]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.33      1.00      0.50         1

    accuracy                           0.33         3
   macro avg       0.17      0.50      0.25         3
weighted avg       0.11      0.33      0.17         3


Class Count:
[3. 4.]

Feature Log Probabilities:
[[-2.89037176 -2.89037176 -2.89037176 -2.89037176 -2.89037176 -2.19722458
  -2.89037176 -2.89037176 -1.79175947 -2.19722458 -2.19722458 -2.19722458]
 [-2.30258509 -2.99573227 -2.99573227 -2.30258509 -2.30258509 -1.89711998
  -2.30258509 -2.99573227 -1.89711998 -2.99573227 -2.99573227 -2.99573227]]

Vocabulary:
['awesome' 'bad' 'boring' 'excellent' 'fantastic' 'film' 'good' 'great'
 'movie' 'poor' 'terrible' 'worst']


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


***5. COMPLEMENT NAIVE BAYES***

In [10]:
print("\n\n########## 5. COMPLEMENT NB ##########")
# USE FOR IMBALANCED TEXT DATA
reviews = [

    "good movie",
    "great movie",
    "awesome movie",
    "excellent movie",
    "fantastic movie",
    "super movie",
    "amazing movie",
    "wonderful movie",
    "nice movie",

    "bad movie"

]

labels = [1,1,1,1,1,1,1,1,1,0]

cv2 = CountVectorizer()

X = cv2.fit_transform(reviews)
y = labels

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

comp_nb = ComplementNB()

evaluate_model(
    "Complement Naive Bayes",
    comp_nb,
    X_train,
    X_test,
    y_train,
    y_test
)

print("\nVocabulary:")
print(cv2.get_feature_names_out())



########## 5. COMPLEMENT NB ##########

COMPLEMENT NAIVE BAYES

Accuracy:
1.0

Confusion Matrix:
[[3]]

Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3


Class Count:
[1. 6.]

Feature Log Probabilities:
[[2.44234704 2.44234704 3.13549422 2.44234704 2.44234704 2.44234704
  3.13549422 1.18958407 3.13549422 3.13549422 2.44234704]
 [2.56494936 2.56494936 1.87180218 2.56494936 2.56494936 2.56494936
  2.56494936 1.87180218 2.56494936 2.56494936 2.56494936]]

Vocabulary:
['amazing' 'awesome' 'bad' 'excellent' 'fantastic' 'good' 'great' 'movie'
 'nice' 'super' 'wonderful']


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


 PRACTICE PREDICTIONS

In [11]:
print("\n\n########## CUSTOM PREDICTIONS ##########")

sample_reviews = [

    "awesome movie",
    "terrible movie",
    "fantastic film",
    "worst film"

]

sample_vectors = cv.transform(sample_reviews)

preds = mnb.predict(sample_vectors)

for review,pred in zip(sample_reviews,preds):

    sentiment = "Positive" if pred==1 else "Negative"

    print(f"\nReview : {review}")
    print(f"Prediction : {sentiment}")



########## CUSTOM PREDICTIONS ##########

Review : awesome movie
Prediction : Positive

Review : terrible movie
Prediction : Negative

Review : fantastic film
Prediction : Positive

Review : worst film
Prediction : Negative


In [ ]:
"""
THINGS TO OBSERVE--->

1. GaussianNB
   - theta_
   - var_

2. BernoulliNB
   - feature_log_prob_
   - class_prior_

3. MultinomialNB
   - feature_log_prob_
   - class_prior_

4. ComplementNB
   - compare with MultinomialNB

5. Try changing alpha

   MultinomialNB(alpha=0.1)
   MultinomialNB(alpha=1)
   MultinomialNB(alpha=10)

   Observe Laplace smoothing effect.

"""